"""empty message

Revision ID: 949691181340
Revises: cf57d171d89f
Create Date: 2024-09-29 17:44:16.538638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949691181340'
down_revision = 'cf57d171d89f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
